//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpAppBE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_qualifications
    {
        public int id { get; set; }
        public string qualification { get; set; }
        public string institution { get; set; }
        public System.DateTime yop { get; set; }
        public decimal percentage { get; set; }
        public int emp_id { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
